apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lbl2ufk9g-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:0f11deb9249097c6c7fb05bf532bd6c94fb7aa47@sha256:affb0fe7e221afe9d1379f2ff3b21ecc833deae2591a8f2ee79c0eb054208526
          name: container-image
